layout_spectrum: 0.4639544
typography_spectrum: 0.03439382
color:
  lightness: 0.83737
  brandStrength: 0.915908
  saturation: 0.7437609
  rhythmicContrast: 0.5837145
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: Pilitratista
