layout_spectrum: 0.3170213
name: Pilitratista
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.03439382
color:
  brandStrength: 0.915908
  lightness: 0.506383
  saturation: 0.506383
  rhythmicContrast: 0.5837145
  brandColors:
    - '#010103'
    - '#304678'
    - '#7C707E'
    - '#DE884B'
    - '#C84013'
